# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Download Patrols
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_events as get_patrol_events,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    set_patrol_status as set_patrol_status,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    set_patrol_types as set_patrol_types,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

er_patrol_types_params = dict(
    patrol_types=...,
)

# %%
# call the task


er_patrol_types = (
    set_patrol_types.set_task_instance_id("er_patrol_types")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_patrol_types_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

er_patrol_status_params = dict(
    status=...,
)

# %%
# call the task


er_patrol_status = (
    set_patrol_status.set_task_instance_id("er_patrol_status")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_patrol_status_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

patrol_obs_params = dict(
    sub_page_size=...,
)

# %%
# call the task


patrol_obs = (
    get_patrol_observations.set_task_instance_id("patrol_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        patrol_types=er_patrol_types,
        status=er_patrol_status,
        include_patrol_details=True,
        raise_on_empty=False,
        **patrol_obs_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

fetch_patrol_events_params = dict(
    event_types=...,
    include_null_geometry=...,
    sub_page_size=...,
    include_display_values=...,
)

# %%
# call the task


fetch_patrol_events = (
    get_patrol_events.set_task_instance_id("fetch_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        patrol_types=er_patrol_types,
        status=er_patrol_status,
        truncate_to_time_range=True,
        raise_on_empty=False,
        **fetch_patrol_events_params,
    )
    .call()
)


# %% [markdown]
# ## Group Data

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Transform Observations to Relocations

# %%
# parameters

patrol_reloc_params = dict()

# %%
# call the task


patrol_reloc = (
    process_relocations.set_task_instance_id("patrol_reloc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        observations=patrol_obs,
        relocs_columns=[
            "patrol_id",
            "patrol_start_time",
            "patrol_end_time",
            "patrol_type__value",
            "patrol_type__display",
            "patrol_serial_number",
            "patrol_status",
            "patrol_subject",
            "groupby_col",
            "fixtime",
            "junk_status",
            "extra__source",
            "geometry",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **patrol_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Style Trajectory By Category

# %%
# parameters

set_patrol_traj_color_column_params = dict()

# %%
# call the task


set_patrol_traj_color_column = (
    set_string_var.set_task_instance_id("set_patrol_traj_color_column")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="patrol_type", **set_patrol_traj_color_column_params)
    .call()
)


# %% [markdown]
# ## Trajectories

# %%
# parameters

patrol_traj_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


patrol_traj = (
    relocations_to_trajectory.set_task_instance_id("patrol_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=patrol_reloc, **patrol_traj_params)
    .call()
)


# %% [markdown]
# ## Add temporal index to Patrol Trajectories

# %%
# parameters

traj_add_temporal_index_params = dict()

# %%
# call the task


traj_add_temporal_index = (
    add_temporal_index.set_task_instance_id("traj_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_traj,
        time_col="extra__patrol_start_time",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **traj_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Rename value grouper columns for Trajectories

# %%
# parameters

traj_rename_grouper_columns_params = dict()

# %%
# call the task


traj_rename_grouper_columns = (
    map_columns.set_task_instance_id("traj_rename_grouper_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_add_temporal_index,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__patrol_type__value": "patrol_type",
            "extra__patrol_serial_number": "patrol_serial_number",
            "extra__patrol_status": "patrol_status",
            "extra__patrol_subject": "patrol_subject",
        },
        **traj_rename_grouper_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Traj Colormap

# %%
# parameters

traj_colormap_params = dict()

# %%
# call the task


traj_colormap = (
    apply_color_map.set_task_instance_id("traj_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_rename_grouper_columns,
        colormap=[
            "#FF9600",
            "#F23B0E",
            "#A100CB",
            "#F04564",
            "#03421A",
            "#3089FF",
            "#E26FFF",
            "#8C1700",
            "#002960",
            "#FFD000",
            "#B62879",
            "#680078",
            "#005A56",
            "#0056C7",
            "#331878",
            "#E76826",
        ],
        input_column_name=set_patrol_traj_color_column,
        output_column_name="patrol_traj_colormap",
        **traj_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Coordinate Filter

# %%
# parameters

filter_fetched_patrol_events_params = dict(
    bounding_box=...,
    filter_point_coords=...,
    reset_index=...,
)

# %%
# call the task


filter_fetched_patrol_events = (
    apply_reloc_coord_filter.set_task_instance_id("filter_fetched_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=fetch_patrol_events,
        roi_gdf=None,
        roi_name=None,
        **filter_fetched_patrol_events_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index to Patrol Events

# %%
# parameters

pe_add_temporal_index_params = dict()

# %%
# call the task


pe_add_temporal_index = (
    add_temporal_index.set_task_instance_id("pe_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_fetched_patrol_events,
        time_col="patrol_start_time",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **pe_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Patrol Events Colormap

# %%
# parameters

pe_colormap_params = dict()

# %%
# call the task


pe_colormap = (
    apply_color_map.set_task_instance_id("pe_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=pe_add_temporal_index,
        input_column_name="event_type",
        colormap="tab20b",
        output_column_name="event_type_colormap",
        **pe_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Cast Patrol Trajectory Columns

# %%
# parameters

patrol_traj_cols_to_string_params = dict()

# %%
# call the task


patrol_traj_cols_to_string = (
    convert_column_values_to_string.set_task_instance_id("patrol_traj_cols_to_string")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_colormap,
        columns=["patrol_serial_number", "patrol_type"],
        **patrol_traj_cols_to_string_params,
    )
    .call()
)


# %% [markdown]
# ## Cast Patrol Events Columns

# %%
# parameters

pe_cols_to_string_params = dict()

# %%
# call the task


pe_cols_to_string = (
    convert_column_values_to_string.set_task_instance_id("pe_cols_to_string")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=pe_colormap,
        columns=["patrol_serial_number", "patrol_type"],
        **pe_cols_to_string_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Coordinate Filter

# %%
# parameters

filter_patrol_events_params = dict(
    bounding_box=...,
    filter_point_coords=...,
    reset_index=...,
)

# %%
# call the task


filter_patrol_events = (
    apply_reloc_coord_filter.set_task_instance_id("filter_patrol_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=fetch_patrol_events,
        roi_gdf=None,
        roi_name=None,
        **filter_patrol_events_params,
    )
    .call()
)


# %% [markdown]
# ## Split Patrol Trajectories by Group

# %%
# parameters

split_patrol_traj_groups_params = dict()

# %%
# call the task


split_patrol_traj_groups = (
    split_groups.set_task_instance_id("split_patrol_traj_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=traj_colormap, groupers=groupers, **split_patrol_traj_groups_params)
    .call()
)


# %% [markdown]
# ## Split Patrol Events by Group

# %%
# parameters

split_pe_groups_params = dict()

# %%
# call the task


split_pe_groups = (
    split_groups.set_task_instance_id("split_pe_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=pe_colormap, groupers=groupers, **split_pe_groups_params)
    .call()
)


# %% [markdown]
# ## Persist Patrol Trajectories as GPKG

# %%
# parameters

persist_traj_gpkg_params = dict()

# %%
# call the task


persist_traj_gpkg = (
    persist_df.set_task_instance_id("persist_traj_gpkg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_traj,
        filename="patrol_trajectories",
        filetype="gpkg",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_traj_gpkg_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Trajectories as Parquet

# %%
# parameters

persist_traj_parquet_params = dict()

# %%
# call the task


persist_traj_parquet = (
    persist_df.set_task_instance_id("persist_traj_parquet")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=patrol_traj,
        filename="patrol_trajectories",
        filetype="geoparquet",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_traj_parquet_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Events as GPKG

# %%
# parameters

persist_events_gpkg_params = dict()

# %%
# call the task


persist_events_gpkg = (
    persist_df.set_task_instance_id("persist_events_gpkg")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_patrol_events,
        filename="patrol_events",
        filetype="gpkg",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_events_gpkg_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Patrol Events as Parquet

# %%
# parameters

persist_events_parquet_params = dict()

# %%
# call the task


persist_events_parquet = (
    persist_df.set_task_instance_id("persist_events_parquet")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_patrol_events,
        filename="patrol_events",
        filetype="geoparquet",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_events_parquet_params,
    )
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Create Event Map Layers

# %%
# parameters

patrol_events_map_layers_params = dict(
    zoom=...,
)

# %%
# call the task


patrol_events_map_layers = (
    create_point_layer.set_task_instance_id("patrol_events_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "event_type_colormap"},
        legend=None,
        tooltip_columns=["patrol_serial_number", "event_type", "time"],
        **patrol_events_map_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=split_pe_groups)
)


# %% [markdown]
# ## Create Trajectory Map Layers

# %%
# parameters

patrol_traj_map_layers_params = dict(
    legend=...,
    zoom=...,
)

# %%
# call the task


patrol_traj_map_layers = (
    create_polyline_layer.set_task_instance_id("patrol_traj_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_width": 3,
            "width_units": "pixels",
            "color_column": "patrol_traj_colormap",
        },
        tooltip_columns=["patrol_serial_number", "patrol_type"],
        **patrol_traj_map_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=split_patrol_traj_groups)
)


# %% [markdown]
# ## Combine Trajectories and Patrol Events layers

# %%
# parameters

combined_traj_and_pe_map_layers_params = dict()

# %%
# call the task


combined_traj_and_pe_map_layers = (
    groupbykey.set_task_instance_id("combined_traj_and_pe_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            all_keyed_iterables_are_skips,
        ],
        unpack_depth=1,
    )
    .partial(
        iterables=[patrol_traj_map_layers, patrol_events_map_layers],
        **combined_traj_and_pe_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Ecomaps

# %%
# parameters

traj_patrol_events_ecomap_params = dict(
    title=...,
    north_arrow_style=...,
    legend_style=...,
    view_state=...,
    widget_id=...,
)

# %%
# call the task


traj_patrol_events_ecomap = (
    draw_ecomap.set_task_instance_id("traj_patrol_events_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=base_map_defs,
        static=False,
        max_zoom=20,
        **traj_patrol_events_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=combined_traj_and_pe_map_layers)
)


# %% [markdown]
# ## Persist Ecomaps

# %%
# parameters

traj_pe_ecomap_html_urls_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


traj_pe_ecomap_html_urls = (
    persist_text.set_task_instance_id("traj_pe_ecomap_html_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **traj_pe_ecomap_html_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=traj_patrol_events_ecomap)
)


# %% [markdown]
# ## Create Ecomap Widgets

# %%
# parameters

traj_pe_map_widgets_single_views_params = dict()

# %%
# call the task


traj_pe_map_widgets_single_views = (
    create_map_widget_single_view.set_task_instance_id(
        "traj_pe_map_widgets_single_views"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Combined Patrol Events and Trajectories",
        **traj_pe_map_widgets_single_views_params,
    )
    .map(argnames=["view", "data"], argvalues=traj_pe_ecomap_html_urls)
)


# %% [markdown]
# ## Merge Ecomap Views

# %%
# parameters

traj_pe_grouped_map_widget_params = dict()

# %%
# call the task


traj_pe_grouped_map_widget = (
    merge_widget_views.set_task_instance_id("traj_pe_grouped_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        widgets=traj_pe_map_widgets_single_views, **traj_pe_grouped_map_widget_params
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard with Patrol Map Widgets

# %%
# parameters

patrol_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


patrol_dashboard = (
    gather_dashboard.set_task_instance_id("patrol_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[traj_pe_grouped_map_widget],
        groupers=groupers,
        time_range=time_range,
        **patrol_dashboard_params,
    )
    .call()
)
