# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class ErPatrolTypes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    patrol_types: List[str] = Field(
        ...,
        description="Specify the patrol type(s) to analyze (optional). Leave empty to analyze all patrol types.",
        title="Patrol Types",
    )


class StatusEnum(str, Enum):
    active = "active"
    overdue = "overdue"
    done = "done"
    cancelled = "cancelled"


class ErPatrolStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Optional[List[StatusEnum]] = Field(
        ["done"],
        description="Choose to analyze patrols with a certain status. If left empty, patrols of all status will be analyzed",
        title="Patrol Status",
    )


class PatrolObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sub_page_size: Optional[int] = Field(
        None,
        description="        Manually set the page size for underlying ER API requests.\n        If left as None, this will use the underlying client default value (4000)\n        ",
        title="Sub Page Size",
    )


class FetchPatrolEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_types: List[str] = Field(
        ...,
        description="Specify the event type(s) to analyze (optional). Leave this section empty to analyze all event types.",
        title="Event Types",
    )
    include_null_geometry: Optional[bool] = Field(
        True, title="Include Events Without a Geometry (point or polygon)"
    )
    sub_page_size: Optional[int] = Field(
        None,
        description="        Manually set the page size for underlying ER API requests.\n        If left as None, this will use the underlying client default value (4000)\n        ",
        title="Sub Page Size",
    )
    include_display_values: Optional[bool] = Field(
        True,
        description="Whether or not to include display values for event types",
        title="Include Display Values",
    )


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps,
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TemporalGrouper(RootModel[str]):
    root: str = Field(..., title="Time")


class ValueGrouper(RootModel[str]):
    root: str = Field(..., title="Category")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class BoundingBox(BaseModel):
    min_y: Optional[float] = Field(-90.0, title="Min Latitude")
    max_y: Optional[float] = Field(90.0, title="Max Latitude")
    min_x: Optional[float] = Field(-180.0, title="Min Longitude")
    max_x: Optional[float] = Field(180.0, title="Max Longitude")


class Coordinate(BaseModel):
    y: float = Field(..., description="Example -0.15293", title="Latitude")
    x: float = Field(..., description="Example 37.30906", title="Longitude")


class Sort(str, Enum):
    ascending = "ascending"
    descending = "descending"


class LegendDefinition(BaseModel):
    label_column: Optional[str] = Field(None, title="Label Column")
    color_column: Optional[str] = Field(None, title="Color Column")
    labels: Optional[List[str]] = Field(None, title="Labels")
    colors: Optional[List[str]] = Field(None, title="Colors")
    sort: Optional[Sort] = Field(None, title="Sort")
    label_suffix: Optional[str] = Field(None, title="Label Suffix")


class Placement(str, Enum):
    top_left = "top-left"
    top_right = "top-right"
    bottom_left = "bottom-left"
    bottom_right = "bottom-right"
    fill = "fill"


class LegendStyle(BaseModel):
    placement: Optional[Placement] = Field("bottom-right", title="Placement")
    title: Optional[str] = Field("Legend", title="Title")
    format_title: Optional[bool] = Field(False, title="Format Title")


class NorthArrowStyle(BaseModel):
    placement: Optional[Placement] = Field("top-left", title="Placement")
    style: Optional[Dict[str, Any]] = Field({"transform": "scale(0.8)"}, title="Style")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper]]] = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard or persisted data.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class PatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class FilterFetchedPatrolEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: Optional[BoundingBox] = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter coordinates to be inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: Optional[List[Coordinate]] = Field(
        [],
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )
    reset_index: Optional[bool] = Field(
        True, description="Reset index after filtering", title="Reset Index"
    )


class FilterPatrolEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: Optional[BoundingBox] = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter coordinates to be inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: Optional[List[Coordinate]] = Field(
        [],
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )
    reset_index: Optional[bool] = Field(
        True, description="Reset index after filtering", title="Reset Index"
    )


class PatrolTrajMapLayers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legend: Optional[LegendDefinition] = Field(
        None,
        description="If present, includes this layer in the map legend",
        title="Legend",
    )


class TrajPatrolEventsEcomap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Optional[str] = Field(
        None,
        description="            The map title. Note this is the title drawn on the map canvas itself, and will result\n            in duplicate titles if set in the context of a dashboard in which the iframe/widget\n            container also has a title set on it.\n            ",
        title="Title",
    )
    north_arrow_style: Optional[NorthArrowStyle] = Field(
        None,
        description="Additional arguments for configuring the North Arrow.",
        title="North Arrow Style",
    )
    legend_style: Optional[LegendStyle] = Field(
        None,
        description="Additional arguments for configuring the legend.",
        title="Legend Style",
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    er_client_name: Optional[ErClientName] = Field(None, title="Data Source")
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_patrol_types: Optional[ErPatrolTypes] = Field(None, title="")
    er_patrol_status: Optional[ErPatrolStatus] = Field(None, title="")
    patrol_obs: Optional[PatrolObs] = Field(None, title="")
    fetch_patrol_events: Optional[FetchPatrolEvents] = Field(None, title="")
    groupers: Optional[Groupers] = Field(None, title="Group Data")
    patrol_traj: Optional[PatrolTraj] = Field(None, title="Trajectories")
    filter_fetched_patrol_events: Optional[FilterFetchedPatrolEvents] = Field(
        None, title="Apply Coordinate Filter"
    )
    filter_patrol_events: Optional[FilterPatrolEvents] = Field(
        None, title="Apply Coordinate Filter"
    )
    base_map_defs: Optional[BaseMapDefs] = Field(None, title="Base Maps")
    patrol_traj_map_layers: Optional[PatrolTrajMapLayers] = Field(
        None, title="Create Trajectory Map Layers"
    )
    traj_patrol_events_ecomap: Optional[TrajPatrolEventsEcomap] = Field(
        None, title="Draw Ecomaps"
    )
